name: diagram
version: git
summary: CLI tool to generate hand written diagrams from ASCII arts.
description: |
  It's a full featured CLI application which converts
  the ASCII text into handwritten drawings. 

grade: devel
confinement: devmode

parts:
  diagram:
    source: .
    plugin: go
    go-packages: 
      - github.com/esimov/diagram

apps:
  diagram: 
    command: diagram